language: python

python:
    - "2.7"

install:
    - "pip install -q -r requirements-dev.txt ."

script:
    - coverage run --source cglims setup.py test

after_success:
    coveralls

notifications:
    email: false
