---
language: python

python:
  - '2.7'

install:
  - pip install -q -r requirements-dev.txt .

script:
  - coverage run --source "$(basename "$PWD")" setup.py test

after_success: coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: robinandeer
  password:
    secure: MnY7XdD6/ZPAraVTFL/FQZ1Qfac6Cb9voFETdyxs+gOr5a2UCx/di4Mql/7kD6I56BufiTE+G69ysp9q1hpZm8M/CXgsF0XBHxXEgu0ECwPSR1+e7e6UME7hciAVPRhhA9paXzfXeTML0t6UjwwClpl3IUVT5Qy5RvVJwOy8Rjs3aSab/cQw/jCTN3B8pLXhE0hIU8Jd5br2cKvCEumOcRsR5CYwNpnKh4RRPyidfjxdpQRD2AgrbI6573xrSLzDj/uwwkpuaW/BaPtQQOpuLAAyKXOOuyGnRpKud8klLrZwjLP6OAyXsjOkAOPpSZJ7ihV1jduJxQdOdW8WQcjzU0S+Ebe4WFJw8+TSbaIrgpvH9eUviDVYZC+Xq56+J6RubBYXGDTLEZZ5C6BycHl+qBfpAQ1PAXQ9wWTFcmQnD/nbOD0AMWbJ5DjnTypafPmwdvWCDygkHAXXrsKSRun8sFQlYodvbK+qbyjJpkkEPqXTGzLOSiH/7Z2Sv1O0wOo4mKIc+ys2EcHvFOnADePvmOnxXoQYiD8QcuLqgMIBxqfwqRS0KALAA5UAtOQcYLN6s2tli6SxgxmdJznPIH5S7tI/KPsCftshe8xMor3Etgfu9BrFqPpKFcrxEAiGESqF/muqc9V/ZuXRnQ7SbaJcur/bwuUNbMj1OYZOnASvLlM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Clinical-Genomics/cglims
